#include "Renderer/StaticModelRenderer.h"
#include "Assets/DdsTextureLoader.h"
#include "Assets/GpuMesh.h"
#include "Assets/GpuTexture.h"
#include "Assets/MaterialAssetLoader.h"
#include "Assets/MeshAssetLoader.h"
#include "Assets/StaticModelAssetLoader.h"
#include <algorithm>
#include <array>
#include <cmath>
#include <cstring>
#include <new>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <vector>

namespace engine::renderer
{
namespace
{
using engine::assets::AssetResult;using engine::graphics::GraphicsResult;
bool Finite(const engine::math::Matrix4&m)noexcept{for(const auto&r:m.m)for(float v:r)if(!std::isfinite(v))return false;return true;}
bool Finite(const engine::math::Vector4&v)noexcept{return std::isfinite(v.x)&&std::isfinite(v.y)&&std::isfinite(v.z)&&std::isfinite(v.w);}
AssetResult Load(engine::assets::AssetManager& manager,engine::assets::AssetLoaderRegistry& registry,const engine::assets::AssetPath& path,const engine::assets::AssetType type,std::unique_ptr<engine::assets::LoadedAsset>& out)noexcept
{engine::assets::AssetHandle handle;auto result=manager.FindByPath(path,handle);if(result==AssetResult::NotFound){engine::assets::AssetMetadata metadata;metadata.path=path;metadata.id=path.GetId();metadata.type=type;result=manager.Register(metadata,handle);}if(engine::assets::Failed(result))return result;if(engine::assets::Failed(result=manager.Load(handle)))return result;const engine::assets::AssetData* data=nullptr;if(engine::assets::Failed(result=manager.GetData(handle,data))||!data)return AssetResult::IoError;engine::assets::AssetMetadata metadata;if(engine::assets::Failed(result=manager.GetMetadata(handle,metadata))||metadata.type!=type)return AssetResult::TypeMismatch;return registry.Load(metadata,*data,out);}
struct alignas(16) FrameCB{float vp[16],cameraTime[4],lightDirectionIntensity[4],lightColor[4],ambientDebug[4];};
struct alignas(16) ObjectCB{float world[16],normal[16],tint[4],objectData[4];};
struct alignas(16) MaterialCB{float base[4],emissive[4],surface[4],specular[4];};
static_assert(sizeof(FrameCB)%16U==0U&&sizeof(ObjectCB)%16U==0U&&sizeof(MaterialCB)%16U==0U);
}

bool StaticModelInstance::IsValid()const noexcept{return model.IsValid()&&Finite(world)&&Finite(tint);}

class StaticModelRenderer::Impl final
{
public:
    struct TextureEntry{engine::assets::AssetPath path;engine::assets::RequestedColorSpace color=engine::assets::RequestedColorSpace::Preserve;std::unique_ptr<engine::assets::GpuTexture> gpu;std::size_t bindings=0;};
    struct Material{engine::assets::MaterialAsset asset;std::array<engine::graphics::TextureHandle,6> textures{};engine::graphics::SamplerHandle sampler;engine::graphics::BufferHandle constants;};
    struct Resource{engine::assets::GpuMesh mesh;std::vector<Material> materials;engine::assets::MeshBounds bounds;engine::graphics::GraphicsBackend backend=engine::graphics::GraphicsBackend::None;std::string name;};
    struct Slot{std::unique_ptr<Resource> resource;std::uint32_t generation=1U;};
    engine::graphics::RenderDevice* device=nullptr;engine::graphics::CommandContext* context=nullptr;engine::graphics::ShaderHandle vs,ps;engine::graphics::InputLayoutHandle layout;std::array<engine::graphics::PipelineStateHandle,6> pipelines{};std::array<engine::graphics::TextureHandle,6> fallbacks{};engine::graphics::BufferHandle frameBuffer,objectBuffer;std::vector<TextureEntry> textureCache;std::unordered_map<std::string,std::size_t> textureLookup;std::vector<Slot> slots;std::vector<std::uint32_t> freeSlots;std::size_t reused=0;
    bool Ready()const noexcept{return device&&context&&vs.IsValid()&&ps.IsValid();}
    std::string Key(const engine::assets::AssetPath&p,const engine::assets::RequestedColorSpace c)const{return p.String()+(c==engine::assets::RequestedColorSpace::Srgb?"|srgb":"|linear");}
    AssetResult Texture(engine::assets::AssetManager& manager,engine::assets::AssetLoaderRegistry& registry,const engine::assets::AssetPath& path,const engine::assets::RequestedColorSpace color,engine::graphics::TextureHandle& out)
    {const auto key=Key(path,color);const auto found=textureLookup.find(key);if(found!=textureLookup.end()){auto&e=textureCache[found->second];++e.bindings;++reused;out=e.gpu->GetHandle();return AssetResult::Success;}std::unique_ptr<engine::assets::LoadedAsset> loaded;auto result=Load(manager,registry,path,engine::assets::AssetType::Texture,loaded);if(engine::assets::Failed(result))return result;auto texture=static_cast<engine::assets::TextureLoadedAsset*>(loaded.get())->ReleaseTexture();TextureEntry entry;entry.path=path;entry.color=color;entry.gpu=std::make_unique<engine::assets::GpuTexture>();engine::assets::GpuTextureUploadOptions options;options.requestedColorSpace=color;if(engine::graphics::Failed(entry.gpu->Upload(*device,texture,options)))return AssetResult::InternalError;entry.bindings=1;out=entry.gpu->GetHandle();const std::size_t index=textureCache.size();textureCache.push_back(std::move(entry));textureLookup.emplace(key,index);return AssetResult::Success;}
    void ReleaseResource(Resource& r)noexcept{for(auto&m:r.materials){if(m.constants.IsValid())(void)device->DestroyBuffer(m.constants);if(m.sampler.IsValid())(void)device->DestroySampler(m.sampler);}r.materials.clear();if(r.mesh.IsValid())(void)r.mesh.Release(*device);}
};

StaticModelRenderer::StaticModelRenderer()noexcept{try{impl_=std::make_unique<Impl>();}catch(...) {}}
StaticModelRenderer::~StaticModelRenderer()noexcept{Shutdown();}
bool StaticModelRenderer::IsInitialized()const noexcept{return impl_&&impl_->Ready();}
GraphicsResult StaticModelRenderer::Initialize(engine::graphics::RenderDevice& device,engine::graphics::CommandContext& context,const engine::assets::ShaderAsset& vertex,const engine::assets::ShaderAsset& pixel)noexcept
{
    if(!impl_||IsInitialized()||!device.IsReady()||!context.IsValid()||!vertex.IsValid()||!pixel.IsValid()||vertex.GetStage()!=engine::graphics::ShaderStage::Vertex||pixel.GetStage()!=engine::graphics::ShaderStage::Pixel)return GraphicsResult::InvalidArgument;impl_->device=&device;impl_->context=&context;
    engine::graphics::ShaderDesc sd;sd.stage=vertex.GetStage();sd.bytecode={vertex.GetBytecode(),vertex.GetBytecodeSize()};sd.debugName=vertex.GetDebugName().c_str();auto result=device.CreateShader(sd,impl_->vs);if(engine::graphics::Failed(result)){Shutdown();return result;}sd.stage=pixel.GetStage();sd.bytecode={pixel.GetBytecode(),pixel.GetBytecodeSize()};sd.debugName=pixel.GetDebugName().c_str();if(engine::graphics::Failed(result=device.CreateShader(sd,impl_->ps))){Shutdown();return result;}
    const engine::graphics::VertexElementDesc elements[]={{"POSITION",0,engine::graphics::Format::R32G32B32Float,0,0,engine::graphics::VertexInputRate::PerVertex,0},{"NORMAL",0,engine::graphics::Format::R32G32B32Float,0,12,engine::graphics::VertexInputRate::PerVertex,0},{"TANGENT",0,engine::graphics::Format::R32G32B32A32Float,0,24,engine::graphics::VertexInputRate::PerVertex,0},{"TEXCOORD",0,engine::graphics::Format::R32G32Float,0,40,engine::graphics::VertexInputRate::PerVertex,0}};engine::graphics::InputLayoutDesc ild{impl_->vs,elements,4U,"StaticModel layout"};if(engine::graphics::Failed(result=device.CreateInputLayout(ild,impl_->layout))){Shutdown();return result;}
    for(std::size_t alpha=0;alpha<3;++alpha)for(std::size_t sided=0;sided<2;++sided){engine::graphics::GraphicsPipelineDesc pd;pd.vertexShader=impl_->vs;pd.pixelShader=impl_->ps;pd.inputLayout=impl_->layout;pd.topology=engine::graphics::PrimitiveTopology::TriangleList;pd.rasterizer.cullMode=sided?engine::graphics::CullMode::None:engine::graphics::CullMode::Back;pd.rasterizer.scissorEnable=true;pd.depthStencil.depthEnable=true;pd.depthStencil.depthWriteEnable=alpha!=2;if(alpha==2){auto&b=pd.blend.renderTargets[0];b.blendEnable=true;b.sourceColor=engine::graphics::BlendFactor::SourceAlpha;b.destinationColor=engine::graphics::BlendFactor::InverseSourceAlpha;b.sourceAlpha=engine::graphics::BlendFactor::One;b.destinationAlpha=engine::graphics::BlendFactor::InverseSourceAlpha;}if(engine::graphics::Failed(result=device.CreateGraphicsPipeline(pd,impl_->pipelines[alpha*2+sided]))){Shutdown();return result;}}
    constexpr std::array<std::uint32_t,6> pixels={0xFFFFFFFFU,0xFFFF8080U,0xFF000000U,0xFFFFFFFFU,0xFF000000U,0xFFFFFFFFU};engine::graphics::TextureDesc td;td.width=td.height=1;td.format=engine::graphics::Format::R8G8B8A8UNorm;td.usage=engine::graphics::ResourceUsage::Immutable;td.bindFlags=engine::graphics::TextureBindFlags::ShaderResource;engine::graphics::TextureSubresourceData init;init.dataSize=init.rowPitch=init.slicePitch=4;for(std::size_t i=0;i<6;++i){init.data=reinterpret_cast<const std::byte*>(&pixels[i]);if(engine::graphics::Failed(result=device.CreateTexture(td,&init,1,impl_->fallbacks[i]))){Shutdown();return result;}}
    engine::graphics::BufferDesc bd;bd.usage=engine::graphics::ResourceUsage::Dynamic;bd.bindFlags=engine::graphics::BufferBindFlags::Constant;bd.cpuAccess=engine::graphics::CpuAccessFlags::Write;bd.byteSize=sizeof(FrameCB);if(engine::graphics::Failed(result=device.CreateBuffer(bd,nullptr,impl_->frameBuffer))){Shutdown();return result;}bd.byteSize=sizeof(ObjectCB);if(engine::graphics::Failed(result=device.CreateBuffer(bd,nullptr,impl_->objectBuffer))){Shutdown();return result;}return GraphicsResult::Success;
}

AssetResult StaticModelRenderer::CreateModel(engine::assets::AssetManager& manager,engine::assets::AssetLoaderRegistry& registry,const engine::assets::AssetPath& path,StaticModelRenderHandle& out)noexcept
{
    out={};if(!IsInitialized()||!path.IsValid())return AssetResult::InvalidArgument;try{std::unique_ptr<engine::assets::LoadedAsset> loaded;auto result=Load(manager,registry,path,engine::assets::AssetType::StaticModel,loaded);if(engine::assets::Failed(result))return result;auto model=static_cast<engine::assets::StaticModelLoadedAsset*>(loaded.get())->ReleaseModel();result=Load(manager,registry,model.GetMeshPath(),engine::assets::AssetType::Mesh,loaded);if(engine::assets::Failed(result))return result;auto mesh=static_cast<engine::assets::MeshLoadedAsset*>(loaded.get())->ReleaseMesh();if(mesh.GetMaterialSlotCount()!=model.GetMaterialCount())return AssetResult::TypeMismatch;auto resource=std::make_unique<Impl::Resource>();if(engine::graphics::Failed(resource->mesh.Upload(*impl_->device,mesh)))return AssetResult::InternalError;resource->bounds=mesh.GetBounds();resource->backend=impl_->device->GetBackend();resource->name=path.String();resource->materials.reserve(model.GetMaterialCount());
    for(std::size_t i=0;i<model.GetMaterialCount();++i){result=Load(manager,registry,model.GetMaterialPath(i),engine::assets::AssetType::Material,loaded);if(engine::assets::Failed(result)){impl_->ReleaseResource(*resource);return result;}Impl::Material m;m.asset=static_cast<engine::assets::MaterialLoadedAsset*>(loaded.get())->ReleaseMaterial();m.textures=impl_->fallbacks;const auto&d=m.asset.GetDesc();const std::array<const std::optional<engine::assets::AssetPath>*,6> paths={&d.baseColorTexture,&d.normalTexture,&d.specularGlossTexture,&d.roughnessTexture,&d.emissiveTexture,&d.specularPowerTexture};for(std::size_t s=0;s<6;++s)if(*paths[s]){const auto color=(s==0||s==4)?engine::assets::RequestedColorSpace::Srgb:engine::assets::RequestedColorSpace::Linear;result=impl_->Texture(manager,registry,**paths[s],color,m.textures[s]);if(engine::assets::Failed(result)){impl_->ReleaseResource(*resource);return result;}}if(engine::graphics::Failed(impl_->device->CreateSampler(d.sampler,m.sampler))){impl_->ReleaseResource(*resource);return AssetResult::InternalError;}MaterialCB cb{};std::memcpy(cb.base,d.baseColorFactor.data(),16);std::memcpy(cb.emissive,d.emissiveFactor.data(),12);cb.emissive[3]=d.emissiveStrength;cb.surface[0]=d.roughnessFactor;cb.surface[1]=d.alphaCutoff;cb.surface[2]=static_cast<float>(d.alphaMode);cb.surface[3]=d.normalScale;cb.specular[0]=d.specularIntensity;cb.specular[1]=d.specularPower;cb.specular[2]=d.reflectionFactor;engine::graphics::BufferDesc bd;bd.byteSize=sizeof(cb);bd.usage=engine::graphics::ResourceUsage::Dynamic;bd.bindFlags=engine::graphics::BufferBindFlags::Constant;bd.cpuAccess=engine::graphics::CpuAccessFlags::Write;if(engine::graphics::Failed(impl_->device->CreateBuffer(bd,nullptr,m.constants))||engine::graphics::Failed(impl_->context->UpdateBuffer(m.constants,&cb,sizeof(cb)))){if(m.constants.IsValid())(void)impl_->device->DestroyBuffer(m.constants);if(m.sampler.IsValid())(void)impl_->device->DestroySampler(m.sampler);impl_->ReleaseResource(*resource);return AssetResult::InternalError;}resource->materials.push_back(std::move(m));}
    std::uint32_t index;if(impl_->freeSlots.empty()){index=static_cast<std::uint32_t>(impl_->slots.size());impl_->slots.emplace_back();}else{index=impl_->freeSlots.back();impl_->freeSlots.pop_back();}auto&slot=impl_->slots[index];slot.resource=std::move(resource);if(slot.generation==0)slot.generation=1;out={index,slot.generation};return AssetResult::Success;}catch(const std::bad_alloc&){return AssetResult::OutOfMemory;}catch(...){return AssetResult::InternalError;}
}

bool StaticModelRenderer::IsModelValid(const StaticModelRenderHandle h)const noexcept{return IsInitialized()&&h.IsValid()&&h.index<impl_->slots.size()&&impl_->slots[h.index].generation==h.generation&&impl_->slots[h.index].resource;}
AssetResult StaticModelRenderer::GetModelBounds(const StaticModelRenderHandle h,engine::assets::MeshBounds& out)const noexcept{out={};if(!h.IsValid())return AssetResult::InvalidArgument;if(!IsModelValid(h))return AssetResult::NotFound;out=impl_->slots[h.index].resource->bounds;return AssetResult::Success;}
AssetResult StaticModelRenderer::DestroyModel(const StaticModelRenderHandle h)noexcept{if(!h.IsValid())return AssetResult::InvalidArgument;if(!IsModelValid(h))return AssetResult::NotFound;auto&s=impl_->slots[h.index];impl_->ReleaseResource(*s.resource);s.resource.reset();++s.generation;if(s.generation==0)++s.generation;impl_->freeSlots.push_back(h.index);return AssetResult::Success;}

GraphicsResult StaticModelRenderer::Render(const RenderView& view,const StaticModelInstance* instances,const std::size_t count,StaticModelRenderStats& stats)noexcept
{
    stats={};stats.submittedInstances=count;if(!IsInitialized()||!view.IsValid()||(count&&instances==nullptr))return GraphicsResult::InvalidArgument;FrameCB frame{};std::memcpy(frame.vp,view.viewProjection.m,sizeof(frame.vp));frame.cameraTime[0]=view.cameraPosition.x;frame.cameraTime[1]=view.cameraPosition.y;frame.cameraTime[2]=view.cameraPosition.z;frame.cameraTime[3]=view.elapsedTime;auto l=view.lightDirection.Normalized();frame.lightDirectionIntensity[0]=l.x;frame.lightDirectionIntensity[1]=l.y;frame.lightDirectionIntensity[2]=l.z;frame.lightDirectionIntensity[3]=view.lightIntensity;frame.lightColor[0]=view.lightColor.x;frame.lightColor[1]=view.lightColor.y;frame.lightColor[2]=view.lightColor.z;frame.ambientDebug[0]=view.ambientColor.x;frame.ambientDebug[1]=view.ambientColor.y;frame.ambientDebug[2]=view.ambientColor.z;frame.ambientDebug[3]=static_cast<float>(view.debugMode);auto result=impl_->context->UpdateBuffer(impl_->frameBuffer,&frame,sizeof(frame));if(engine::graphics::Failed(result))return result;(void)impl_->context->SetConstantBuffers(engine::graphics::ShaderStage::Vertex,0,&impl_->frameBuffer,1);(void)impl_->context->SetConstantBuffers(engine::graphics::ShaderStage::Pixel,0,&impl_->frameBuffer,1);
    struct Draw{const StaticModelInstance*i;Impl::Resource*r;const engine::assets::MeshSubmesh*s;Impl::Material*m;std::size_t alpha;float distance;};std::vector<Draw> draws;std::unordered_set<const Impl::Resource*> unique;try{for(std::size_t n=0;n<count;++n){const auto&i=instances[n];if(!i.visible)continue;if(!i.IsValid()||!IsModelValid(i.model)){++stats.rejectedInvalidInstances;continue;}engine::math::Matrix4 inverse;if(!i.world.TryInverse(inverse)){++stats.rejectedInvalidInstances;continue;}auto*r=impl_->slots[i.model.index].resource.get();unique.insert(r);++stats.acceptedInstances;for(std::size_t s=0;s<r->mesh.GetSubmeshCount();++s){const auto*sub=r->mesh.GetSubmesh(s);if(!sub||sub->materialSlot>=r->materials.size())continue;auto*m=&r->materials[sub->materialSlot];const auto alpha=static_cast<std::size_t>(m->asset.GetDesc().alphaMode);const auto center=i.world.TransformPoint({r->bounds.sphereCenter[0],r->bounds.sphereCenter[1],r->bounds.sphereCenter[2]});const auto dx=center.x-view.cameraPosition.x,dy=center.y-view.cameraPosition.y,dz=center.z-view.cameraPosition.z;draws.push_back({&i,r,sub,m,alpha,dx*dx+dy*dy+dz*dz});}}}catch(...){return GraphicsResult::OutOfMemory;}
    std::sort(draws.begin(),draws.end(),[](const Draw&a,const Draw&b){if(a.alpha!=b.alpha)return a.alpha<b.alpha;if(a.alpha==2)return a.distance>b.distance;if(a.r!=b.r)return a.r<b.r;if(a.m!=b.m)return a.m<b.m;return a.i->objectId<b.i->objectId;});const Impl::Resource* lastResource=nullptr;const Impl::Material* lastMaterial=nullptr;engine::graphics::PipelineStateHandle lastPipeline;const StaticModelInstance*lastInstance=nullptr;
    for(const auto&d:draws){const auto pipeline=impl_->pipelines[d.alpha*2+(d.m->asset.GetDesc().doubleSided?1:0)];if(pipeline!=lastPipeline){if(engine::graphics::Failed(result=impl_->context->SetGraphicsPipeline(pipeline)))return result;lastPipeline=pipeline;++stats.pipelineChanges;}if(d.r!=lastResource){engine::graphics::VertexBufferBinding vb{d.r->mesh.GetVertexBuffer(),d.r->mesh.GetVertexStride(),0};engine::graphics::IndexBufferBinding ib{d.r->mesh.GetIndexBuffer(),0};if(engine::graphics::Failed(result=impl_->context->SetVertexBuffers(0,&vb,1))||engine::graphics::Failed(result=impl_->context->SetIndexBuffer(ib)))return result;lastResource=d.r;++stats.meshChanges;}if(d.i!=lastInstance){engine::math::Matrix4 inverse;if(!d.i->world.TryInverse(inverse))continue;ObjectCB object{};std::memcpy(object.world,d.i->world.m,sizeof(object.world));const auto normal=inverse.Transposed();std::memcpy(object.normal,normal.m,sizeof(object.normal));object.tint[0]=d.i->tint.x;object.tint[1]=d.i->tint.y;object.tint[2]=d.i->tint.z;object.tint[3]=d.i->tint.w;object.objectData[0]=static_cast<float>(d.i->objectId);if(engine::graphics::Failed(result=impl_->context->UpdateBuffer(impl_->objectBuffer,&object,sizeof(object))))return result;(void)impl_->context->SetConstantBuffers(engine::graphics::ShaderStage::Vertex,1,&impl_->objectBuffer,1);(void)impl_->context->SetConstantBuffers(engine::graphics::ShaderStage::Pixel,1,&impl_->objectBuffer,1);lastInstance=d.i;}if(d.m!=lastMaterial){(void)impl_->context->SetConstantBuffers(engine::graphics::ShaderStage::Pixel,2,&d.m->constants,1);(void)impl_->context->SetShaderResources(engine::graphics::ShaderStage::Pixel,0,d.m->textures.data(),6);(void)impl_->context->SetSamplers(engine::graphics::ShaderStage::Pixel,0,&d.m->sampler,1);lastMaterial=d.m;++stats.materialChanges;}if(engine::graphics::Failed(result=impl_->context->DrawIndexed(d.s->indexCount,d.s->firstIndex,d.s->baseVertex)))return result;++stats.drawCalls;stats.triangles+=d.s->indexCount/3;if(d.alpha==0)++stats.opaqueDraws;else if(d.alpha==1)++stats.maskDraws;else ++stats.blendDraws;}
    stats.uniqueModelResources=unique.size();stats.uniqueGpuTextures=impl_->textureCache.size();stats.reusedTextureBindings=impl_->reused;return GraphicsResult::Success;
}

void StaticModelRenderer::Unbind()noexcept{if(!impl_||!impl_->context)return;(void)impl_->context->UnbindConstantBuffers(engine::graphics::ShaderStage::Vertex,0,3);(void)impl_->context->UnbindConstantBuffers(engine::graphics::ShaderStage::Pixel,0,3);(void)impl_->context->UnbindShaderResources(engine::graphics::ShaderStage::Pixel,0,6);(void)impl_->context->UnbindSamplers(engine::graphics::ShaderStage::Pixel,0,1);impl_->context->UnbindGraphicsPipeline();}
void StaticModelRenderer::Shutdown()noexcept
{
    if(!impl_)return;Unbind();if(impl_->device){for(auto&s:impl_->slots)if(s.resource){impl_->ReleaseResource(*s.resource);s.resource.reset();}for(auto&e:impl_->textureCache)if(e.gpu)(void)e.gpu->Release(*impl_->device);impl_->textureCache.clear();impl_->textureLookup.clear();for(auto&t:impl_->fallbacks)if(t.IsValid())(void)impl_->device->DestroyTexture(t);if(impl_->frameBuffer.IsValid())(void)impl_->device->DestroyBuffer(impl_->frameBuffer);if(impl_->objectBuffer.IsValid())(void)impl_->device->DestroyBuffer(impl_->objectBuffer);for(auto&p:impl_->pipelines)if(p.IsValid())(void)impl_->device->DestroyGraphicsPipeline(p);if(impl_->layout.IsValid())(void)impl_->device->DestroyInputLayout(impl_->layout);if(impl_->ps.IsValid())(void)impl_->device->DestroyShader(impl_->ps);if(impl_->vs.IsValid())(void)impl_->device->DestroyShader(impl_->vs);}impl_->slots.clear();impl_->freeSlots.clear();impl_->device=nullptr;impl_->context=nullptr;impl_->vs={};impl_->ps={};impl_->layout={};impl_->pipelines={};impl_->fallbacks={};impl_->frameBuffer={};impl_->objectBuffer={};impl_->reused=0;
}
}
